version: '3'

services:
    lz_worker:
        build: "./lz_worker/"
        image: "lz_worker:latest"
        depends_on:
            - lz_api

    lz_api:
        build: "./lz_api/"
        image: "lz_api:latest"
        ports:
            - "8081:5000"
        depends_on:
            - lz_api_mongodb

    lz_api_mongodb:
        image: "mongo:latest"

    # for debugging / development
    mongo-express:
        image: "mongo-express"
        ports:
            - "8082:8081"
        environment:
            - ME_CONFIG_MONGODB_SERVER=lz_api_mongodb
        depends_on:
            - lz_api_mongodb

    # lz_frontend:
    #     build: "./lz_frontend/"
    #     image: "lz_frontend:latest"
    #     ports:
    #         - "8080:80"
