version: '3'

services:
    lz_worker:
        build: "./lz_worker/"
        image: "lz_worker:latest"

    lz_api:
        build: "./lz_api/"
        image: "lz_api:latest"
        ports:
            - "8081:5000"

    # lz_api_mongodb:
    #     image: "mongodb:latest"

    # lz_frontend:
    #     build: "./lz_frontend/"
    #     image: "lz_frontend:latest"
    #     ports:
    #         - "8080:80"
