version: '3'

services:
    lz_worker:
        build: "./lz_worker/"
        image: "lz_worker:latest"

    # lz_api:

    # lz_api_mongodb:
    #     image: "mongodb:latest"

    # lz_frontend:
    #     build: "./lz_frontend/"
    #     ports:
    #         - "8080:80"
