# 10 DEBUG    - shows bot output
# 20 INFO     - normal
# 30 WARNING  - mistakes
# 40 ERROR    - script errors
log_level: 20

config:
  wipe_comments: True  # Store True if you want to wipe comments

  move_from: 1
  move_till: 500

  stop_on_winrate: 0.95       # Stops analysis on this winrate drop

  analyze_time: 120            # How many seconds to use per game moves analysis (default=60)
  analyze_threshold: 0.025     # Display analysis on moves losing at least this much of win rate (default=0.05)

  variations_threshold: 0.05   # Explore variations on moves losing at least this much of win rate (default=0.05)

  variations_time: 60         # How many seconds to use per variations analysis (default=30)
  variations_depth: 3         # Number of nodes to explore (depth) in each variation tree (default=5)
  num_to_show: 10             # Number of suggested perfect moves to show(default=10)

  move_list_threshold: 0.2    # This filters suggested move list by at least this probability

bots:
  default: leela-zero  # store here the config which will be used if --bot is not defined

  template:
    bot_type: TYPE_OF_BOT_ENGINE  # Only one of {leela, leela-zero}
    executable: FULL_PATH_TO_EXECUTABLE  # Python requires forward slashes '/' in path
    arguments:  ANY_VALID_BOT_ARGUMENT  # for more info see bot help: leela --help or leelaz --help

  leela-zero:  # LeelaZero also requires weights
    bot_type: leela-zero
    executable: leelaz
    arguments: --gtp --noponder --weights /opt/leelaz_weights/network.gz
